#!/bin/bash

clear
start=~/Documents/startpage/
tree=~/Documents/treepage/
minimal=~/Documents/minimal/

while :; do
	printf "Install dependencies? (y/n)\n"
	read dep
	if [ $dep = "y" ]; then
		sudo pacman -S foliate zathura youtube-dl discord git bspwm i3-gaps alacritty sxhkd dmenu lxappearance cmus feh mpv neovim scrot qutebrowser w3m xdotool pavucontrol npm python python-dbus polybar gnome-screenshot noto-fonts-emoji xorg-xsetroot binutils make gcc pkg-config fakeroot autoconf automake yay
		cd ~ && git clone https://github.com/wmutils/opt && cd ~/opt/ && make && sudo make install
		rm -rf ~/opt/
		git clone https://github.com/jasonliang-dev/dmenu/ && cd ~/dmenu/ && sudo make install
		rm -rf ~/dmenu/
		yay -S ponymix betterdiscordctl pywal-git i3lock-color-git corrupter-git xwinwrap-git spotify themix-gui spicetify-cli picom-jonaburg-git
		clear
		printf "\nDependencies installed succesfully!\n\n"
		break
	elif [ $dep = "n" ]; then
		break
	else
		clear
		continue 2;
	fi
done
break;
clear
while :; do
        printf "Do you wish to change shell? (y/n)\n"
        read shell
	printf "\n"
        if [ $shell = "y" ]; then
                chsh
		break
        elif [ $shell = "n" ]; then
                break
	else
                clear
                continue 2;
	fi
done
break;
clear

printf "/usr/bin/\n"
printf "/usr/share/nvim/runtime/colors/\n"
printf "Open a new terminal and give permission to these folders by typing: sudo chown (your username) /usr/bin/ & sudo chown (your username) /usr/share/nvim/runtime/colors/\n\n"
sudo chown jujey /usr/bin/
sudo chown jujey /usr/share/nvim/runtime/colors/

while :; do
	printf "Copy & paste config files? (y/n)\n"
	read cpfiles
	if [ $cpfiles = "y" ]; then
		cp -r ~/dots/home/jujey/config/alacritty/ ~/.config/
		cp -r ~/dots/home/jujey/config/bspwm ~/.config/
		cp -r ~/dots/home/jujey/config/i3 ~/.config/
		cp -r ~/dots/home/jujey/config/nvim ~/.config/
		cp -r ~/dots/home/jujey/config/picom ~/.config/
		cp -r ~/dots/home/jujey/config/polybar ~/.config/
		cp -r ~/dots/home/jujey/config/qutebrowser ~/.config/
		cp -r ~/dots/home/jujey/config/sxhkd ~/.config/
		cp -r ~/dots/home/jujey/config/mimeapps.list ~/.config/
		cp -r ~/dots/home/jujey/config/spicetify ~/.config/
		cp -r ~/dots/home/jujey/.bashrc ~/
		cp -r ~/dots/home/jujey/dmen.sh ~/
		cp -r ~/dots/home/jujey/lock ~/
		cp -r ~/dots/home/jujey/.vimrc ~/
	elif [ $cpfiles = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done


while :; do
	printf "Install custom startpages? (y/n)\n"
	read pages
	if [ $pages = "y" ]; then
		rm -rf $start
		rm -rf $tree
		rm -rf $minimal

		mkdir ~/Documents/startpage/
		cp -r ~/dots/home/jujey/Documents/startpage/min.css ~/Documents/startpage/
		cp -r ~/dots/home/jujey/Documents/startpage/min.html ~/Documents/startpage/

		mkdir ~/Documents/minimal/
		cp -r ~/dots/home/jujey/Documents/minimal/style.css ~/Documents/minimal/
		cp -r ~/dots/home/jujey/Documents/minimal/page.html ~/Documents/minimal/

		mkdir ~/Documents/treepage/
		cp -r ~/dots/home/jujey/Documents/treepage/tree.css ~/Documents/treepage/
		cp -r ~/dots/home/jujey/Documents/treepage/tree.html ~/Documents/treepage/
	elif [ $pages = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done

while :; do
	printf "Install borders, fff & whatsapp? (y/n)\n"
	read bfw
	if [ $bfw = "y" ]; then
		cp ~/dots/usr/bin/borders /usr/bin/
		cp ~/dots/usr/bin/fff /usr/bin/
		cp ~/dots/usr/bin/whatsapp /usr/bin/
	elif [ $bfw = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done
clear
printf "Giving permission to executables...\n\n"
sudo chmod a+rx ~/dmen.sh & sudo chmod a+rx ~/lock & sudo chmod a+rx ~/.config/polybar/launch.sh & sudo chmod a+rx /usr/bin/borders & sudo chmod a+rx ~/.config/bspwm/bspwmrc & sudo chmod a+rx ~/.config/sxhkd/sxhkdrc & sudo chmod a+rx /usr/bin/fff & sudo chmod a+rx /usr/bin/whatsapp
clear
while :; do
	printf "Install vim plugins? (y/n)\n"
	read vim
	if [ $vim = "y" ]; then
		sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
		       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
		clear
		printf "The installation has been completed successfully!\n"
		printf "Don't forget to type ':PlugInstall' inside Vim/Nvim after the installation!\n\n"
		break
	elif [ $vim = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done
cd ~
clear

while :; do
	printf "Install bitmap fonts pack? (y/n)\n"
	read bitmap
	if [ $bitmap = "y" ]; then
		printf "Installing bitmap fonts...\n\n"
		sleep 1
		git clone https://github.com/Tecate/bitmap-fonts.git
		cd bitmap-fonts
		sudo cp -avr bitmap/ /usr/share/fonts
		xset fp+ /usr/share/fonts/bitmap
		fc-cache -fv
		cd /etc/fonts/conf.d/
		sudo rm /etc/fonts/conf.d/10*  
		sudo rm -rf 70-no-bitmaps.conf 
		sudo ln -s ../conf.avail/70-yes-bitmaps.conf .
		sudo dpkg-reconfigure fontconfig
		break
	elif [ $bitmap = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done
cd ~
clear
while :; do
	printf "Install pywal on discord/spotify/gui/vim? (y/n)\n"
	read pywalwal
	if [ $pywalwal = "y" ]; then
		clear
		printf "Applying pywal themes...\n\n"
		sleep 1
		betterdiscordctl install
		git clone https://github.com/guglicap/wal-discord.git
		chmod +x ./wal-discord/wal-discord
		ln -s "`pwd`/wal-discord/wal-discord" /usr/bin/
		cd ~

		cp ~/dots/usr/share/nvim/runtime/colors/wal.vim /usr/share/nvim/runtime/colors/wal.vim
		sudo chown jujey /opt/ && sudo chown jujey /opt/spotify && sudo chown jujey /opt/spotify/Apps/
		spicetify && spicetify backup apply enable-devtool && spicetify update
	
		clear
		printf "Applying pywal on gui...\n\n"
		sleep 1
		cd ~
		break
	elif [ $pywalwal = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done
cd ~
clear

while :; do
	printf "Apply/update pywal? (y/n)\n"
	read appwal
	if [ $appwal = "y" ]; then
		clear
		cp -r ~/dots/home/jujey/Pictures/waves.jpg ~/Pictures/
		cp -r ~/dots/home/jujey/Pictures/spirited.jpg ~/Pictures/
		wal -i ~/Pictures/spirited.jpg -l
		wal -R
		themix-gui
		wal-discord -t -u
	elif [ $appwal = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done
clear
printf "Installation completed!\n\n"
