#!/bin/bash

clear
start=~/Documents/startpage/
tree=~/Documents/treepage/
rm -rf $start
rm -rf $tree

while :; do
	printf "Install dependencies? (y/n)\n"
	read dep
	if [ $dep = "y" ]; then
		sudo pacman -S discord git bspwm alacritty ponymix sxhkd dmenu lxappearance cmus feh mpv neovim scrot git qutebrowser w3m xdotool pavucontrol npm python python-dbus polybar gnome-screenshot noto-fonts-emoji xorg-xsetroot binutils make gcc pkg-config fakeroot autoconf automake yay chromium
		curl -sS https://download.spotify.com/debian/pubkey.gpg | gpg --import -
		pamac build spotify
		pip install xinput-gui
		yay -S betterdiscordctl pywal-git i3lock-color-git corrupter-git xwinwrap-git libxft-bgra-git
		cd ~ && git clone https://github.com/wmutils/opt && cd ~/opt/ && make && sudo make install
		rm -rf ~/opt/
		clear
		printf "\nDependencies installed succesfully!\n\n"
		break
	elif [ $dep = "n" ]; then
		break
	else
		clear
		continue 2;
	fi
done
break;
clear
while :; do
        printf "Do you wish to change shell? (y/n)\n"
        read shell
	printf "\n"
        if [ $shell = "y" ]; then
                chsh
        elif [ $shell = "n" ]; then
                break
	else
                clear
                continue 2;
	fi
done
break;
clear
sudo chown jujey /usr/bin/
sudo chown jujey /usr/share/nvim/runtime/colors/

cp -r ~/dots/home/jujey/config/alacritty/ ~/.config/
cp -r ~/dots/home/jujey/config/bspwm ~/.config/
cp -r ~/dots/home/jujey/config/nvim ~/.config/
cp -r ~/dots/home/jujey/config/picom ~/.config/
cp -r ~/dots/home/jujey/config/polybar ~/.config/
cp -r ~/dots/home/jujey/config/qutebrowser ~/.config/
cp -r ~/dots/home/jujey/config/sxhkd ~/.config/
cp -r ~/dots/home/jujey/config/mimeapps.list ~/.config/
cp -r ~/dots/home/jujey/config/spicetify ~/.config/
cp -r ~/dots/home/jujey/.bashrc ~/
cp -r ~/dots/home/jujey/dmen.sh ~/
cp -r ~/dots/home/jujey/lock ~/
cp -r ~/dots/home/jujey/.vimrc ~/

mkdir ~/Documents/startpage/
cp -r ~/dots/home/jujey/Documents/startpage/min.css ~/Documents/startpage/
cp -r ~/dots/home/jujey/Documents/startpage/min.html ~/Documents/startpage/

mkdir ~/Documents/treepage/
cp -r ~/dots/home/jujey/Documents/treepage/tree.css ~/Documents/treepage/
cp -r ~/dots/home/jujey/Documents/treepage/tree.html ~/Documents/treepage/

cp -r ~/dots/home/jujey/Pictures/me.jpg ~/Pictures/
cp -r ~/dots/home/jujey/Pictures/me2.jpg ~/Pictures/
cp -r ~/dots/home/jujey/Pictures/me3.png ~/Pictures/
cp -r ~/dots/home/jujey/Pictures/me4.jpg ~/Pictures/
cp -r ~/dots/home/jujey/Pictures/sea.png ~/Pictures/
cp -r ~/dots/home/jujey/Pictures/charl-folscher-TvzGlW0a2qY-unsplash.jpg ~/Pictures/

cp ~/dots/usr/share/nvim/runtime/colors/wal.vim /usr/share/nvim/runtime/colors/wal.vim
cp ~/dots/usr/bin/borders /usr/bin/
cp ~/dots/usr/bin/fff /usr/bin/
cp ~/dots/usr/bin/whatsapp /usr/bin/

sudo chmod a+rx ~/dmen.sh & sudo chmod a+rx ~/lock & sudo chmod a+rx ~/.config/polybar/launch.sh & sudo chmod a+rx /usr/bin/borders & sudo chmod a+rx ~/.config/bspwm/bspwmrc & sudo chmod a+rx ~/.config/sxhkd/sxhkdrc & sudo chmod a+rx /usr/bin/fff & sudo chmod a+rx /usr/bin/whatsapp
clear
while :; do
	printf "Install vim plugins? (y/n)\n"
	read vim
	if [ $vim = "y" ]; then
		sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
		       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
		clear
		printf "The installation has been completed successfully!\n"
		printf "Don't forget to type ':PlugInstall' when opening vim for the first time!\n\n"
		break
	elif [ $vim = "n" ]; then
		clear
		break
	else
		continue 2
	fi
done
cd ~
clear
printf "Installing bitmap fonts...\n\n"
sleep 1
git clone https://github.com/Tecate/bitmap-fonts.git
cd bitmap-fonts
sudo cp -avr bitmap/ /usr/share/fonts
xset fp+ /usr/share/fonts/bitmap
fc-cache -fv
cd /etc/fonts/conf.d/
sudo rm /etc/fonts/conf.d/10*  
sudo rm -rf 70-no-bitmaps.conf 
sudo ln -s ../conf.avail/70-yes-bitmaps.conf .
sudo dpkg-reconfigure fontconfig
cd ~

clear
printf "Applying pywal themes...\n\n"
sleep 1
betterdiscordctl install
git clone https://github.com/guglicap/wal-discord.git
chmod +x ./wal-discord/wal-discord
ln -s "`pwd`/wal-discord/wal-discord" /usr/bin/
wal-discord -u -t
cd ~

sudo chown jujey /opt/ && sudo chown jujey /opt/spotify && sudo chown jujey /opt/spotify/Apps/
spicetify && spicetify backup apply enable-devtool && spicetify update

clear
printf "Applying pywal on gui...\n\n"
sleep 1
cd ~
git clone https://github.com/themix-project/oomox.git --recursive
cd oomox
make -f po.mk install
./gui.sh
cd ~
clear
printf "Installation completed!\n\n"
