window:
        dimensions:
          columns: 60
          lines: 25
        padding:
                y: 10
                x: 10

font:
        normal:
                family: Terminus
                style: Regular
        size: 12

        bold:
                family: Terminus
                style: Bold
        size: 12

cursor:
        style: Block
        blinking: Always
        blink_interval: 750
        unfocused_hollow: true

shell:
        program: /bin/bash
        args:
                - --login
