window:
        dimensions:
          columns: 60
          lines: 25
        padding:
                y: 10
                x: 10

font:
        normal:
                family: MonacoB2
                style: Regular
        size: 10

        bold:
                family: MonacoB2
                style: Regular
        size: 10

cursor:
        style: Block
        blinking: Always
        blink_interval: 750
        unfocused_hollow: true

shell:
        program: /bin/bash
        args:
                - --login
