#!/usr/bin/env bash
tmpbg="/tmp/screen.png"
scrot "$tmpbg"; corrupter "$tmpbg" "$tmpbg"
i3lock --timecolor=ffffffff --datecolor=ffffffff --ringcolor=ffffff10 --keyhlcolor=ffffff95 --separatorcolor=ffffff00 --insidevercolor=00000099 --insidewrongcolor=00000099 --linecolor=20202099 --veriftext="" --wrongtext="" -k -i "$tmpbg"; rm "$tmpbg"
