#!/usr/bin/env bash
tmpbg="/tmp/screen.png"
scrot "$tmpbg"; corrupter "$tmpbg" "$tmpbg"
i3lock --time-color=ffffffff --date-color=ffffffff --ring-color=ffffff10 --keyhl-color=ffffff95 --separator-color=ffffff00 --insidever-color=00000099 --insidewrong-color=00000099 --line-color=20202099 --verif-text="" --wrong-text="" -k -i "$tmpbg"; rm "$tmpbg"
